url = https://online.actitime.com/nothing/login.do

browser = chrome

username = pratyushmohanty2004@gmail.com
password = Pratyush123

environment = qa

excelPath = ./src/test/resources/ActitimeData.xlsx

screenshotPath = ./failedscreenshot/